Css search input
Sanya486/cinemania_by_DevTeam pull request #22
Opened 2023-06-09 05:17 UTC by Shprinher

2023-06-09 09:27 UTC, Sanya486 requested changes

2023-06-09 09:27 UTC, Sanya486 commented on src/partials/catalog/search.html
>              <select class="year-of-film-search-form" id="yearOfFilm" name="yearOfFilm">
я думаю тут варто підключити якусь бібліотеку, щоб вона виглядала нормально. Зможешь додати?

2023-06-09 15:44 UTC, Shprinher commented on src/partials/catalog/search.html
>              <select class="year-of-film-search-form" id="yearOfFilm" name="yearOfFilm">
пробую не дуже виходить

2023-06-09 19:50 UTC, Sanya486 requested changes

2023-06-09 19:50 UTC, Sanya486 commented on package.json
> +    "flatpickr": "^4.6.13",
Видали будь ласка та завантаж флетпикер до devDependencies. `npm i --save-dev flatpickr`

2023-06-10 13:53 UTC, demonikos approved these changes

2023-06-10 13:54 UTC, demonikos commented on src/partials/catalog/search.html
>              <select class="year-of-film-search-form" id="yearOfFilm" name="yearOfFilm">
Саш, з твого дозволу пушим, щодо бібліотеки - вирішим вже по факту як працюватиме цей MVP

2023-06-10 13:54 UTC, demonikos approved these changes

2023-06-10 14:57 UTC, closed without merging